### ISSUE TITLE
Fetch code from upstream

### ISSUE THREAD

**Issue by jaseemabid** [fabric8-jenkins/jenkins-openshift-base#10] opened 2018-01-15 11:29 UTC
This fork is quite behind the upstream. As of now,  This branch is 30 commits ahead, 211 commits behind openshift:master.

**Comment by lordofthejars** [comment] 2018-03-23 11:58
@jaseemabid I am going to start working on this one

**Comment by lordofthejars** [comment] 2018-03-23 15:49
@jaseemabid I have been updating the repo, and there are some conflicts in `s2i/run` script. In particular the part of copying/removing configuration files and copying/removing plugins. I think that updating at this time these parts of the script, when recently we had some problems there, it is not so smart. So I will advocate for just park this issue if it is not really really necessary. Let's be conservative for now and not add new unknown problems.

**Comment by jaseemabid** [comment] 2018-03-23 19:39
@lordofthejars Sounds fair. I'll also look for fixes upstream that we could pull down.

**Comment by rupalibehera** [comment] 2018-07-28 20:43
duplicate of this https://github.com/openshiftio/openshift.io/issues/3861 it has been tracked in 3861

**Closed** 2018-07-28 20:43 UTC
